import { formatMoney } from '@/shared/domain';
import type { ThemeColors } from '@/shared/design-tokens';
import { useQuery } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { Image, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { PortalButton, PortalCard, PortalMetric, PortalShell, StatusBadge } from '@/components/business/business-ui';
import { BusinessProductCard, businessCollections } from '@/components/business/business-products';
import { getB2BCatalog, getOrders } from '@/lib/api';
import { useAppState } from '@/state/app-context';
import { useAuth } from '@/state/auth-context';
import { useBusinessStyles } from '@/theme/business-theme';

export default function BusinessHomeScreen() {
  const router = useRouter();
  const styles = useBusinessStyles(createStyles);
  const { width } = useWindowDimensions();
  const compact = width < 700;
  const { cartCount } = useAppState();
  const { token, user } = useAuth();
  const businessEnabled = user?.role === 'BUSINESS' && Boolean(token);
  const catalogEnabled = !user || businessEnabled;
  const ordersQuery = useQuery({ queryKey: ['orders', user?.id], queryFn: () => getOrders(token!), enabled: businessEnabled, refetchInterval: 5000 });
  const catalog = useQuery({ queryKey: ['catalog', 'b2b', 'home', user?.id], queryFn: () => getB2BCatalog(token ?? undefined, { limit: 100, offset: 0, sort: 'newest' }), enabled: catalogEnabled });
  const orders = ordersQuery.data ?? [];
  const categoryRails = [...businessCollections.map((collection) => collection.name), 'Others']
    .map((category) => ({
      category,
      products: (catalog.data ?? []).filter((product) => category === 'PVC & Plumbing'
        ? product.category === 'PVC & Plumbing' || product.category === 'PVC PIPE'
        : product.category === category),
    }))
    .filter((section) => section.products.length > 0);
  function shop(category?: string) { router.push({ pathname: '/business/catalog', params: category ? { category } : {} }); }
  return <PortalShell eyebrow="YOUR BUSINESS, WELL SUPPLIED" title={`Good to see you${user?.name ? `, ${user.name.split(' ')[0]}` : ''}.`} copy="A fresh start for your next restock, renovation, or big project.">
    <View style={[styles.hero, compact && { padding: 24 }]}><View style={styles.heroCopy}><View style={styles.heroPill}><Text style={styles.heroPillText}>THE WHOLESALE EDIT</Text></View><Text accessibilityRole="header" style={[styles.heroTitle, compact && { fontSize: 36, lineHeight: 42 }]}>Big on quality.{'\n'}Better in bulk.</Text><Text style={styles.heroDescription}>Stock your shelves. Supply your site. Discover everyday essentials at prices made for business.</Text><View style={styles.heroActions}><PortalButton label="Explore wholesale  →" onPress={() => shop()} /><Pressable accessibilityRole="link" onPress={() => router.push('/business/orders')} style={styles.heroLink}><Text style={styles.heroLinkText}>Track your orders ↗</Text></Pressable></View><Text style={styles.heroFootnote}>Hardware  /  Electrical  /  Paint  /  PVC PIPE & more</Text></View><View style={[styles.heroDisplay, compact && { minHeight: 220, flexBasis: 250 }]}><View style={styles.heroCircle} /><Image source={businessCollections[1].image} resizeMode="contain" style={styles.heroImageBack} /><Image source={businessCollections[3].image} resizeMode="contain" style={styles.heroImageFront} /><View style={styles.heroTag}><Text style={styles.heroTagTitle}>Ready for your next project.</Text><Text style={styles.heroTagCopy}>Everyday essentials. Business prices.</Text></View></View></View>
    <View style={styles.benefits}>{[['↘', 'Wholesale value', 'Your business price, upfront'], ['▤', 'Clear buying terms', 'Minimum quantities on every product'], ['✓', 'GST-ready orders', 'Made for business purchasing'], ['↗', 'Stay in the loop', 'From approval to delivery']].map(([icon, title, copy]) => <View key={title} style={styles.benefit}><Text style={styles.benefitIcon}>{icon}</Text><View style={{ flex: 1 }}><Text style={styles.benefitTitle}>{title}</Text><Text style={styles.benefitCopy}>{copy}</Text></View></View>)}</View>
    <View style={styles.sectionHeading}><View><Text style={styles.eyebrow}>ALL THE RIGHT ESSENTIALS</Text><Text accessibilityRole="header" style={styles.sectionTitle}>Shop for the work ahead.</Text></View><Pressable accessibilityRole="link" onPress={() => shop()} style={styles.textLink}><Text style={styles.linkText}>All categories ↗</Text></Pressable></View>
    <View style={styles.categories}>{businessCollections.map(collection => <Pressable key={collection.name} accessibilityRole="link" onPress={() => shop(collection.name)} style={({ pressed }) => [styles.category, { width: width >= 1100 ? '15.4%' : width >= 600 ? '31.5%' : '47.5%' }, pressed && { opacity: 0.75 }]}><View style={styles.categoryImage}><Image source={collection.image} resizeMode="contain" style={styles.categoryPhoto} /></View><Text style={styles.categoryName}>{collection.name === 'PVC & Plumbing' ? 'PVC PIPE' : collection.name}</Text><Text style={styles.categoryCaption}>{collection.caption}</Text></Pressable>)}</View>
    {catalog.isLoading ? <PortalCard title="Finding your next essentials…" copy="Your wholesale selection is on its way." /> : null}
    {catalog.isError ? <PortalCard title="Products could not be loaded" copy="Please try again to see the current wholesale selection."><PortalButton label="Try again" secondary onPress={() => void catalog.refetch()} /></PortalCard> : null}
    {!catalog.isLoading && !catalog.isError && !catalog.data?.length ? <PortalCard title="New essentials are on their way" copy="Explore the catalogue to find what is available for your next project."><PortalButton label="Explore catalogue" onPress={() => shop()} /></PortalCard> : null}
    {categoryRails.map(({ category, products: categoryProducts }) => <View key={`category-rail-${category}`} style={styles.categoryRailSection}><View style={styles.sectionHeading}><View><Text style={styles.eyebrow}>SHOP BY CATEGORY</Text><Text accessibilityRole="header" style={styles.sectionTitle}>{category === 'PVC & Plumbing' ? 'PVC PIPE' : category}</Text></View><Pressable accessibilityRole="link" onPress={() => shop(category)} style={styles.textLink}><Text style={styles.linkText}>View all {category === 'PVC & Plumbing' ? 'PVC PIPE' : category} ↗</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.productRail}>{categoryProducts.map(product => <BusinessProductCard key={product.id} product={product} style={{ width: compact ? 156 : 285 }} />)}</ScrollView></View>)}
    <View style={styles.editorial}><View style={styles.editorialBody}><Text style={styles.editorialEyebrow}>FROM YOUR FIRST ORDER TO YOUR NEXT BIG PROJECT</Text><Text style={styles.editorialTitle}>One store. More possibilities.</Text><Text style={styles.editorialCopy}>Bring your materials together in one bulk cart, review your quantities, and send your order for approval.</Text></View><PortalButton label={`Review bulk cart${cartCount ? ` (${cartCount})` : ''}  →`} onPress={() => router.push('/business/cart')} /></View>
    <View style={styles.sectionHeading}><View><Text style={styles.eyebrow}>YOUR BUYING SNAPSHOT</Text><Text accessibilityRole="header" style={styles.sectionTitle}>Business as usual, made easier.</Text></View></View>
    <View style={styles.metrics}><PortalMetric value={ordersQuery.isSuccess ? String(orders.length) : '—'} label="Business orders" /><PortalMetric value={ordersQuery.isSuccess ? String(orders.filter(order => (order.approvalStatus ?? 'PENDING') === 'PENDING').length) : '—'} label="Awaiting approval" /><PortalMetric value={ordersQuery.isSuccess ? String(orders.filter(order => order.status === 'DELIVERED').length) : '—'} label="Delivered orders" /><PortalMetric value={String(cartCount)} label="Units in your cart" /></View>
    <PortalCard title="Your latest orders" copy="Pick up where you left off. Follow every order from approval to arrival.">
      {ordersQuery.isLoading ? <Text style={styles.meta}>Loading your orders…</Text> : null}
      {ordersQuery.isError ? <><Text style={styles.meta}>Your orders could not be loaded.</Text><PortalButton label="Reload orders" secondary onPress={() => void ordersQuery.refetch()} /></> : null}
      {ordersQuery.isSuccess && !orders.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>Your first bulk order starts here.</Text><Text style={styles.meta}>Discover your essentials and we’ll keep your orders organised here.</Text><PortalButton label="Start shopping" onPress={() => shop()} /></View> : null}
      {orders.slice(0, 3).map(order => <Pressable key={order.id} accessibilityRole="link" onPress={() => router.push('/business/orders')} style={styles.orderRow}><View style={styles.orderBody}><Text style={styles.orderId}>Order {order.id}</Text><Text numberOfLines={2} style={styles.meta}>{order.items.map(item => `${item.quantity} × ${item.productName}`).join(' · ')}</Text><Text style={styles.orderDate}>{new Date(order.createdAt).toLocaleDateString('en-IN')} · {order.itemCount} units</Text></View><View style={styles.orderSummary}><Text style={styles.orderTotal}>{formatMoney(order.totalInPaise)}</Text><StatusBadge label={(order.approvalStatus ?? 'PENDING') === 'PENDING' ? 'Awaiting approval' : order.approvalStatus === 'REJECTED' ? 'Rejected' : order.status} tone={order.approvalStatus === 'REJECTED' ? 'danger' : order.status === 'DELIVERED' ? 'success' : 'warning'} /></View></Pressable>)}
      {orders.length ? <PortalButton label="View all orders →" secondary onPress={() => router.push('/business/orders')} /> : null}
    </PortalCard>
  </PortalShell>;
}

const createStyles = (c: ThemeColors) => StyleSheet.create({
  hero: { backgroundColor: '#EAF0F5', borderRadius: 24, padding: 40, flexDirection: 'row', flexWrap: 'wrap', overflow: 'hidden', gap: 16 }, heroCopy: { flexGrow: 1.2, flexShrink: 1, flexBasis: 380, zIndex: 1 }, heroPill: { alignSelf: 'flex-start', backgroundColor: '#FFFFFF', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 8 }, heroPillText: { color: '#345B7C', fontSize: 10, letterSpacing: 1.5, fontWeight: '800' }, heroTitle: { color: '#182D45', fontSize: 56, lineHeight: 62, fontWeight: '800', letterSpacing: -2, marginTop: 20 }, heroDescription: { color: '#52677C', fontSize: 16, lineHeight: 25, maxWidth: 450, marginTop: 18 }, heroActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, alignItems: 'center', marginTop: 26 }, heroLink: { minHeight: 44, justifyContent: 'center' }, heroLinkText: { color: '#182D45', fontSize: 13, fontWeight: '700' }, heroFootnote: { color: '#627185', fontSize: 11, lineHeight: 18, marginTop: 24 }, heroDisplay: { flexGrow: 1, flexShrink: 1, flexBasis: 350, minHeight: 330, justifyContent: 'center' }, heroCircle: { position: 'absolute', width: 300, height: 300, borderRadius: 150, backgroundColor: '#D8E4ED', right: 0, top: 10 }, heroImageBack: { position: 'absolute', width: '65%', height: '77%', top: 0, right: 0, transform: [{ rotate: '8deg' }] }, heroImageFront: { position: 'absolute', width: '65%', height: '80%', left: 0, bottom: 16, transform: [{ rotate: '-7deg' }] }, heroTag: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 15, position: 'absolute', right: 0, bottom: 0, maxWidth: '100%' }, heroTagTitle: { color: '#182D45', fontSize: 12, fontWeight: '800' }, heroTagCopy: { color: '#627185', fontSize: 10, marginTop: 5 },
  benefits: { flexDirection: 'row', flexWrap: 'wrap', gap: 22, paddingVertical: 8, paddingBottom: 28, borderBottomWidth: 1, borderColor: c.line }, benefit: { flexGrow: 1, flexBasis: 230, flexDirection: 'row', alignItems: 'center', gap: 12 }, benefitIcon: { color: c.teal, fontSize: 25, width: 34, textAlign: 'center' }, benefitTitle: { color: c.cream, fontSize: 13, fontWeight: '700' }, benefitCopy: { color: c.muted, fontSize: 11, marginTop: 5 }, sectionHeading: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'flex-end', gap: 12, marginTop: 16 }, eyebrow: { color: c.copper, fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginBottom: 8 }, sectionTitle: { color: c.cream, fontSize: 27, lineHeight: 35, fontWeight: '800', letterSpacing: -0.8 }, textLink: { minHeight: 44, justifyContent: 'center' }, linkText: { color: c.teal, fontSize: 13, fontWeight: '700' }, categories: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12 }, category: { paddingBottom: 10 }, categoryImage: { backgroundColor: c.surfaceSunken, borderRadius: 18, height: 150, overflow: 'hidden' }, categoryPhoto: { width: '100%', height: '100%' }, categoryName: { color: c.cream, fontSize: 15, fontWeight: '700', marginTop: 14 }, categoryCaption: { color: c.muted, fontSize: 11, marginTop: 5 }, productRail: { gap: 18, paddingBottom: 8 }, categoryRailSection: { gap: 18, paddingTop: 20 }, editorial: { backgroundColor: '#203C55', padding: 30, borderRadius: 20, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 24 }, editorialBody: { flex: 1, minWidth: 230, gap: 12 }, editorialEyebrow: { color: '#B9D1E4', fontSize: 10, letterSpacing: 1.1, fontWeight: '700' }, editorialTitle: { color: '#FFFFFF', fontSize: 29, lineHeight: 36, fontWeight: '700' }, editorialCopy: { color: '#C8D9E7', fontSize: 14, lineHeight: 23, maxWidth: 650 }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, meta: { color: c.muted, fontSize: 13, lineHeight: 21 }, empty: { alignItems: 'flex-start', paddingVertical: 16, gap: 14 }, emptyTitle: { color: c.cream, fontSize: 18, fontWeight: '700' }, orderRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 16, borderTopWidth: 1, borderColor: c.line, paddingVertical: 18 }, orderBody: { flex: 1, minWidth: 200, gap: 6 }, orderId: { color: c.cream, fontSize: 13, fontWeight: '700' }, orderDate: { color: c.muted, fontSize: 11 }, orderSummary: { alignItems: 'flex-end', gap: 10 }, orderTotal: { color: c.cream, fontSize: 18, fontWeight: '800' },
});

