import * as SecureStore from 'expo-secure-store';
import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react';
import { Platform } from 'react-native';

export type Language = 'en' | 'hi';

const STORAGE_KEY = 'sirohi-language';

const translations: Record<string, string> = {
  Home: 'होम',
  Shop: 'शॉप',
  Cart: 'कार्ट',
  Account: 'अकाउंट',
  'My orders': 'मेरे ऑर्डर',
  'Saved products': 'सेव किए गए प्रोडक्ट्स',
  'Shopping cart': 'शॉपिंग कार्ट',
  items: 'आइटम',
  'Continue with your account': 'अपने अकाउंट के साथ जारी रखें',
  'Built for everyday projects.': 'हर रोज के प्रोजेक्ट्स के लिए बनाया गया।',
  'GST-ready checkout  ·  Pay on delivery': 'GST-ready चेकआउट  ·  डिलीवरी पर भुगतान',
  'Help & support': 'मदद और सपोर्ट',
  'All categories': 'सभी कैटेगरी',
  'Filter by categories': 'कैटेगरी से फ़िल्टर करें',
  'Today’s deals ↗': 'आज के ऑफ़र ↗',
  'Find a technician': 'टेक्नीशियन खोजें',
  'Explore bulk products': 'बल्क प्रोडक्ट्स देखें',
  'Sign in': 'साइन इन',
  Register: 'रजिस्टर',
  'Sign in / Register': 'साइन इन / रजिस्टर',
  'My account': 'मेरा अकाउंट',
  'Track & manage': 'ट्रैक और मैनेज करें',
  'Your account': 'आपका अकाउंट',
  'Orders & account': 'ऑर्डर और अकाउंट',
  'Choose at checkout': 'चेकआउट पर चुनें',
  'Search products, brands and categories': 'प्रोडक्ट, ब्रांड और कैटेगरी खोजें',
  'What are you looking for today?': 'आज आप क्या ढूंढ रहे हैं?',
  'Search store': 'स्टोर खोजें',
  'Recent searches': 'हाल की खोजें',
  'Switch to light mode': 'लाइट मोड पर जाएं',
  'Switch to dark mode': 'डार्क मोड पर जाएं',
  'Light mode': 'लाइट मोड',
  'Dark mode': 'डार्क मोड',
  CONTACT: 'संपर्क',
  COMPANY: 'कंपनी',
  POLICIES: 'नीतियां',
  'THE SHOP': 'शॉप',
  'YOUR SIROHI': 'आपका सिरोही',
  'A LITTLE EXTRA HELP': 'थोड़ी और मदद',
  'Good finds. Great projects.': 'अच्छे प्रोडक्ट्स। शानदार प्रोजेक्ट्स।',
  'Materials, home essentials and expert help. All in one place.': 'मटेरियल, होम एसेंशियल्स और एक्सपर्ट मदद—सब एक ही जगह।',
  'Find your next essential  ↗': 'अपना अगला जरूरी प्रोडक्ट खोजें  ↗',
  'About Us': 'हमारे बारे में',
  'Contact Us': 'हमसे संपर्क करें',
  'All Products': 'सभी प्रोडक्ट्स',
  'Store Locator': 'स्टोर लोकेटर',
  'Terms & Conditions': 'नियम और शर्तें',
  'Privacy Policy': 'प्राइवेसी पॉलिसी',
  'Refund & Cancellation Policy': 'रिफंड और कैंसिलेशन पॉलिसी',
  'Shipping Policy': 'शिपिंग पॉलिसी',
  Warranty: 'वारंटी',
  'Make the most of your materials with a specialist for your project.': 'अपने प्रोजेक्ट के लिए विशेषज्ञ की मदद से मटेरियल का बेहतर इस्तेमाल करें।',
  'Find a technician  →': 'टेक्नीशियन खोजें  →',
  'Shop with confidence': 'भरोसे के साथ खरीदारी करें',
  'Clear prices & stock': 'साफ कीमत और स्टॉक',
  'Easy checkout': 'आसान चेकआउट',
  'GST-ready orders': 'GST-ready ऑर्डर',
  'Made for your project': 'आपके प्रोजेक्ट के लिए',
  'Materials + expert help': 'मटेरियल + एक्सपर्ट मदद',
  'More ways to save': 'बचत के और तरीके',
  'Discover current offers': 'मौजूदा ऑफ़र देखें',
  'FIND YOUR EVERYDAY ESSENTIALS': 'आपकी रोजमर्रा की जरूरतें',
  'Good things, by category': 'कैटेगरी के हिसाब से अच्छे प्रोडक्ट्स',
  'Explore all categories': 'सभी कैटेगरी देखें',
  'Explore collection  →': 'कलेक्शन देखें  →',
  'LITTLE PRICES. BIG POSSIBILITIES.': 'छोटी कीमतें। बड़ी संभावनाएं।',
  'Today’s deals & great finds': 'आज के ऑफ़र और शानदार खोज',
  'Fresh inspiration for your next upgrade. Explore savings and handpicked essentials.': 'आपके अगले अपग्रेड के लिए नई प्रेरणा। बचत और चुने हुए जरूरी प्रोडक्ट्स देखें।',
  'Finding good things for your project…': 'आपके प्रोजेक्ट के लिए अच्छे प्रोडक्ट्स खोज रहे हैं…',
  'We couldn’t load the products. Please try again.': 'प्रोडक्ट्स लोड नहीं हो सके। कृपया फिर कोशिश करें।',
  'Retry products': 'प्रोडक्ट्स फिर लोड करें',
  'New finds are on their way. Browse our collections in the meantime.': 'नए प्रोडक्ट्स जल्द आ रहे हैं। तब तक हमारे कलेक्शन देखें।',
  'SHOP BY CATEGORY': 'कैटेगरी के हिसाब से खरीदें',
  'WORTH A CLOSER LOOK': 'ध्यान से देखने लायक',
  'Find your next favourite': 'अपना अगला पसंदीदा खोजें',
  'A HELPING HAND, WHEN YOU NEED ONE': 'जरूरत पर मदद हमेशा मौजूद',
  'Find a technician for your repairs, installations and finishing touches.': 'रिपेयर, इंस्टॉलेशन और फिनिशिंग के लिए टेक्नीशियन खोजें।',
  'View all products': 'सभी प्रोडक्ट्स देखें',
  'Shop current deals': 'आज के ऑफ़र देखें',
  'The right materials.\nThe right person for the job.': 'सही मटेरियल।\nसही काम के लिए सही व्यक्ति।',
  'Your saved products': 'आपके सेव किए गए प्रोडक्ट्स',
  'Results for': 'इसके परिणाम',
  'Filtered products': 'फ़िल्टर किए गए प्रोडक्ट्स',
  results: 'परिणाम',
  'Clear search': 'सर्च साफ करें',
  Saved: 'सेव किए गए',
  'Sort by': 'इसके अनुसार सॉर्ट करें',
  Recommended: 'अनुशंसित',
  'Price: Low': 'कीमत: कम',
  'Price: High': 'कीमत: ज्यादा',
  'Top Rated': 'सबसे अच्छी रेटिंग',
  'Filter by price': 'कीमत से फ़िल्टर करें',
  Clear: 'साफ करें',
  Min: 'न्यूनतम',
  Max: 'अधिकतम',
  Apply: 'लागू करें',
  Showing: 'दिखा रहे हैं',
  any: 'कोई भी',
  'Loading products…': 'प्रोडक्ट्स लोड हो रहे हैं…',
  'Unable to load products from the backend': 'बैकएंड से प्रोडक्ट्स लोड नहीं हो सके',
  'Unknown error': 'अज्ञात त्रुटि',
  'Products are unavailable.': 'प्रोडक्ट्स उपलब्ध नहीं हैं।',
  'No saved products yet.': 'अभी कोई सेव किया हुआ प्रोडक्ट नहीं है।',
  'No products match this search.': 'इस सर्च से कोई प्रोडक्ट नहीं मिला।',
  'Check the API connection and try again.': 'API कनेक्शन जांचें और फिर कोशिश करें।',
  'Try another category or clear your current filters.': 'दूसरी कैटेगरी आजमाएं या मौजूदा फ़िल्टर हटाएं।',
  'Clear filters': 'फ़िल्टर साफ करें',
  'Filter by category': 'कैटेगरी से फ़िल्टर करें',
  selected: 'चयनित',
  'Clear all filters': 'सभी फ़िल्टर साफ करें',
  'Loading categories…': 'कैटेगरी लोड हो रही हैं…',
  'Categories could not be loaded.': 'कैटेगरी लोड नहीं हो सकीं।',
  Retry: 'फिर कोशिश करें',
  'Active filters': 'सक्रिय फ़िल्टर',
  Categories: 'कैटेगरी',
  Subcategories: 'सबकैटेगरी',
  'No fixed subcategories for the selected category.': 'चुनी हुई कैटेगरी के लिए कोई तय सबकैटेगरी नहीं है।',
  'Order submitted': 'ऑर्डर सबमिट हो गया',
  item: 'आइटम',
  'Your order is awaiting admin approval.': 'आपका ऑर्डर एडमिन की मंजूरी का इंतजार कर रहा है।',
  'Loading your cart…': 'आपका कार्ट लोड हो रहा है…',
  'Cart products are unavailable.': 'कार्ट के प्रोडक्ट्स उपलब्ध नहीं हैं।',
  'Your cart is empty.': 'आपका कार्ट खाली है।',
  'Your order now appears in the account panel, where you can review its products, total and status.': 'आपका ऑर्डर अब अकाउंट पैनल में दिख रहा है, जहां आप प्रोडक्ट्स, कुल राशि और स्टेटस देख सकते हैं।',
  'The cart uses the current product catalogue from the backend. Check the API connection and try again.': 'कार्ट बैकएंड के मौजूदा प्रोडक्ट कैटलॉग का उपयोग करता है। API कनेक्शन जांचें और फिर कोशिश करें।',
  'Add products from the store, then review quantities, delivery and payment here.': 'स्टोर से प्रोडक्ट जोड़ें, फिर यहां मात्रा, डिलीवरी और भुगतान देखें।',
  'Track your order': 'अपना ऑर्डर ट्रैक करें',
  'Continue shopping': 'खरीदारी जारी रखें',
  'Quantities can be changed before you place the order': 'ऑर्डर देने से पहले मात्रा बदली जा सकती है',
  'Clear cart': 'कार्ट साफ करें',
  'in stock': 'स्टॉक में',
  'Installation available': 'इंस्टॉलेशन उपलब्ध',
  'Material only': 'सिर्फ मटेरियल',
  'Price details': 'कीमत की जानकारी',
  'Total amount': 'कुल राशि',
  'Pay on delivery': 'डिलीवरी पर भुगतान',
  'Pay with Razorpay': 'Razorpay से भुगतान',
  'Cash on delivery is unavailable for one or more products in this cart. Online payment is available.': 'इस कार्ट के एक या अधिक प्रोडक्ट्स के लिए कैश ऑन डिलीवरी उपलब्ध नहीं है। ऑनलाइन भुगतान उपलब्ध है।',
  'Continue to Razorpay': 'Razorpay पर जाएं',
  'Place order': 'ऑर्डर करें',
  'GST invoice · Verified fulfilment · Support included': 'GST इनवॉइस · सत्यापित पूर्ति · सपोर्ट शामिल',
  'Create your account': 'अपना अकाउंट बनाएं',
  'Welcome back': 'वापसी पर स्वागत है',
  'Save your details for faster checkout, easy order tracking, and a better way to shop.': 'तेज चेकआउट, आसान ऑर्डर ट्रैकिंग और बेहतर खरीदारी के लिए अपनी जानकारी सेव करें।',
  'Shop products, access orders, and checkout.': 'प्रोडक्ट्स खरीदें, ऑर्डर देखें और चेकआउट करें।',
  'SECURE CUSTOMER ACCOUNT': 'सुरक्षित ग्राहक अकाउंट',
  'QUICK CHECKOUT': 'तेज चेकआउट',
  'FULL NAME': 'पूरा नाम',
  'Your name': 'आपका नाम',
  'PHONE (OPTIONAL)': 'फोन (वैकल्पिक)',
  EMAIL: 'ईमेल',
  PASSWORD: 'पासवर्ड',
  'At least 8 characters': 'कम से कम 8 अक्षर',
  'Create account': 'अकाउंट बनाएं',
  'Already registered? Sign in': 'पहले से रजिस्टर्ड हैं? साइन इन करें',
  'New customer? Create account': 'नए ग्राहक हैं? अकाउंट बनाएं',
  'Choose a different role': 'कोई दूसरा रोल चुनें',
  'Sign in as a customer to buy products.': 'प्रोडक्ट खरीदने के लिए ग्राहक के रूप में साइन इन करें।',
  INSTALLATION: 'इंस्टॉलेशन',
  Only: 'सिर्फ',
  left: 'बाकी',
  'In stock': 'स्टॉक में उपलब्ध',
  'in cart': 'कार्ट में',
  'Add to cart': 'कार्ट में जोड़ें',
  'Add the matching pro': 'संबंधित एक्सपर्ट जोड़ें',
  essentials: 'एसेंशियल्स',
  '20% OFF': '20% की छूट',
  'PAINT & FINISHES': 'पेंट और फिनिश',
  'Fresh walls. Better moods.': 'नई दीवारें। बेहतर एहसास।',
  'Paints, primers and waterproofing for your next room refresh.': 'आपके अगले रूम रिफ्रेश के लिए पेंट, प्राइमर और वॉटरप्रूफिंग।',
  'Wall paints · Primers · Waterproofing': 'वॉल पेंट · प्राइमर · वॉटरप्रूफिंग',
  'Fast delivery on local stock': 'लोकल स्टॉक पर तेज डिलीवरी',
  'SAVE MORE': 'ज्यादा बचत',
  'BATHROOM ESSENTIALS': 'बाथरूम एसेंशियल्स',
  'Small details. Big difference.': 'छोटी चीजें। बड़ा फर्क।',
  'Reliable sanitaryware and fittings for a cleaner everyday space.': 'साफ-सुथरे रोजमर्रा के स्पेस के लिए भरोसेमंद सेनेटरीवेयर और फिटिंग्स।',
  'Faucets · Basins · Bathroom fittings': 'नल · बेसिन · बाथरूम फिटिंग्स',
  'Fast delivery, project-ready picks': 'तेज डिलीवरी, प्रोजेक्ट के लिए तैयार प्रोडक्ट्स',
  'BUY 1 GET 1': 'एक खरीदें, एक पाएं',
  'ELECTRICAL PICKS': 'इलेक्ट्रिकल प्रोडक्ट्स',
  'Make the switch to better.': 'बेहतर विकल्प चुनें।',
  'Trusted switches, wires and essentials for every corner of home.': 'घर के हर कोने के लिए भरोसेमंद स्विच, वायर और एसेंशियल्स।',
  'Switches · Wires · Lighting': 'स्विच · वायर · लाइटिंग',
  'Fast delivery on everyday essentials': 'रोजमर्रा के एसेंशियल्स पर तेज डिलीवरी',
  'PROJECT VALUE': 'प्रोजेक्ट वैल्यू',
  'HARDWARE & TOOLS': 'हार्डवेयर और टूल्स',
  'Build it strong from the start.': 'शुरुआत से मजबूत बनाएं।',
  'The practical hardware that keeps every repair and project moving.': 'हर रिपेयर और प्रोजेक्ट के लिए उपयोगी हार्डवेयर।',
  'Tools · Fasteners · Hardware': 'टूल्स · फास्टनर्स · हार्डवेयर',
  'Fast delivery for urgent fixes': 'जरूरी रिपेयर के लिए तेज डिलीवरी',
  'UP TO 25% OFF': '25% तक की छूट',
  'LIGHTING & ELECTRONICS': 'लाइटिंग और इलेक्ट्रॉनिक्स',
  'A brighter way to come home.': 'घर आने का एक उजला तरीका।',
  'Useful lighting and electronics with value built into every pick.': 'हर चयन में बेहतर कीमत वाली उपयोगी लाइटिंग और इलेक्ट्रॉनिक्स।',
  'LEDs · Fixtures · Electronics': 'LED · फिक्स्चर · इलेक्ट्रॉनिक्स',
  'Fast delivery on selected products': 'चुने हुए प्रोडक्ट्स पर तेज डिलीवरी',
  'PROJECT READY': 'प्रोजेक्ट के लिए तैयार',
  'PVC & PLUMBING': 'PVC और प्लंबिंग',
  'Keep every plan flowing.': 'हर प्लान को आसानी से आगे बढ़ाएं।',
  'Durable fittings for repairs, upgrades and new beginnings.': 'रिपेयर, अपग्रेड और नई शुरुआत के लिए टिकाऊ फिटिंग्स।',
  'Pipes · Fittings · Plumbing': 'पाइप · फिटिंग्स · प्लंबिंग',
  'BULK ORDERS': 'बल्क ऑर्डर्स',
  'Tell us what you need.\nGet the best prices.': 'हमें बताएं आपको क्या चाहिए।\nसबसे अच्छी कीमत पाएं।',
  'Made for builders, shop owners, and contractors who need material at good prices.': 'बिल्डर्स, दुकानदारों और अच्छे दाम पर मटेरियल चाहने वाले कॉन्ट्रैक्टर्स के लिए।',
  'Low prices': 'कम कीमतें',
  'Fixed rates': 'तय रेट',
  'Personal helper': 'पर्सनल हेल्पर',
  'Pay later': 'बाद में भुगतान',
  'GST bill': 'GST बिल',
  'Explore products in bulk': 'बल्क में प्रोडक्ट्स देखें',
  'Tell us what you need': 'हमें बताएं आपको क्या चाहिए',
  'Write down what you need in the app.': 'ऐप में अपनी जरूरत लिखें।',
  'Sellers will reply': 'सेलर्स जवाब देंगे',
  'Many sellers will send you their best prices.': 'कई सेलर्स अपनी सबसे अच्छी कीमत भेजेंगे।',
  'Pick the best one': 'सबसे अच्छा चुनें',
  'See all prices together and pick the cheapest one.': 'सभी कीमतें साथ देखें और सबसे सस्ता चुनें।',
  'Order is done': 'ऑर्डर पूरा करें',
  'Confirm your order, set delivery date, and track it.': 'ऑर्डर कन्फर्म करें, डिलीवरी डेट तय करें और ट्रैक करें।',
  'FRESH OFFERS FOR YOUR NEXT PROJECT': 'आपके अगले प्रोजेक्ट के नए ऑफ़र',
  'Little extras. Lovely savings.': 'छोटी एक्स्ट्रा चीजें। शानदार बचत।',
  'Tap a flyer to explore': 'देखने के लिए फ्लायर पर टैप करें',
  'LIMITED-TIME SAVINGS': 'सीमित समय की बचत',
  'Make room for a fresh new look.': 'नए लुक के लिए जगह बनाएं।',
  'Save on selected project essentials and start your next upgrade today.': 'चुने हुए प्रोजेक्ट एसेंशियल्स पर बचत करें और आज अपना अगला अपग्रेड शुरू करें।',
  'Shop the offer': 'ऑफ़र खरीदें',
  'EVERYDAY FAVOURITES': 'रोजमर्रा के पसंदीदा',
  'BUY 1 GET 1 FREE': 'एक खरीदें, एक मुफ्त पाएं',
  'Double the good stuff.': 'अच्छी चीजें दोगुनी।',
  'Pick your everyday favourites and get more value for every project.': 'अपने रोजमर्रा के पसंदीदा चुनें और हर प्रोजेक्ट में ज्यादा वैल्यू पाएं।',
  'Explore favourites': 'पसंदीदा देखें',
  'THE WEEKEND PROJECT': 'वीकेंड प्रोजेक्ट',
  'New mood.\nOne fresh coat.': 'नया मूड।\nपेंट का एक नया कोट।',
  'Explore paints  →': 'पेंट्स देखें  →',
  'DETAILS THAT DO MORE': 'ज्यादा काम करने वाली डिटेल्स',
  'Everyday essentials.\nExtraordinary feel.': 'रोजमर्रा के एसेंशियल्स।\nअसाधारण एहसास।',
  'Shop sanitaryware  →': 'सेनेटरीवेयर खरीदें  →',
  'SMART PAINT TOOLS': 'स्मार्ट पेंट टूल्स',
  'Estimate it. Preview it. Then buy it.': 'अनुमान लगाएं। प्रीव्यू करें। फिर खरीदें।',
  'Know exactly how much paint you need, then preview a shade on your wall before you buy.': 'जानें कि आपको कितना पेंट चाहिए और खरीदने से पहले दीवार पर शेड का प्रीव्यू देखें।',
  'Paint calculator': 'पेंट कैलकुलेटर',
  'Enter your wall size — we work out litres, product list and cost.': 'दीवार का साइज डालें—हम लीटर, प्रोडक्ट लिस्ट और कीमत निकाल देंगे।',
  'Wall length (ft)': 'दीवार की लंबाई (फीट)',
  'Wall height (ft)': 'दीवार की ऊंचाई (फीट)',
  'Number of walls': 'दीवारों की संख्या',
  Coats: 'कोट',
  'Paint type': 'पेंट का प्रकार',
  'Add materials to cart': 'मटेरियल कार्ट में जोड़ें',
  'Virtual paint preview': 'वर्चुअल पेंट प्रीव्यू',
  'Tap a shade to preview it on the wall before a single can is bought.': 'एक भी कैन खरीदने से पहले दीवार पर शेड का प्रीव्यू देखने के लिए टैप करें।',
  'Your living room wall': 'आपके लिविंग रूम की दीवार',
  'Selected shade': 'चुना हुआ शेड',
  'Choose your language': 'अपनी भाषा चुनें',
  'Select the language you want to use on Sirohi Point.': 'Sirohi Point पर इस्तेमाल करने के लिए भाषा चुनें।',
  'English': 'English',
  'Hindi': 'हिंदी',
  Continue: 'जारी रखें',
  'Back to shop  ↗': 'शॉप पर वापस जाएं  ↗',
  'By continuing, you agree to shop with Sirohi Point securely.': 'जारी रखकर आप Sirohi Point पर सुरक्षित खरीदारी से सहमत हैं।',
  'All products': 'सभी प्रोडक्ट्स',
  Hardware: 'हार्डवेयर',
  Electrical: 'इलेक्ट्रिकल',
  Electronics: 'इलेक्ट्रॉनिक्स',
  Paint: 'पेंट',
  'PVC PIPE': 'PVC पाइप',
  Sanitary: 'सेनेटरी',
  Others: 'अन्य',
};

type LanguageContextValue = {
  language: Language | null;
  hydrated: boolean;
  chooseLanguage: (language: Language) => void;
  t: (text: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: PropsWithChildren) {
  const [language, setLanguage] = useState<Language | null>(null);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    let mounted = true;
    async function load() {
      const value = Platform.OS === 'web'
        ? (typeof window === 'undefined' ? null : window.localStorage.getItem(STORAGE_KEY))
        : await SecureStore.getItemAsync(STORAGE_KEY);
      if (!mounted) return;
      if (value === 'en' || value === 'hi') setLanguage(value);
      setHydrated(true);
    }
    void load();
    return () => { mounted = false; };
  }, []);

  function chooseLanguage(nextLanguage: Language) {
    setLanguage(nextLanguage);
    if (Platform.OS === 'web') {
      try { window.localStorage.setItem(STORAGE_KEY, nextLanguage); } catch { /* Keep the choice for this session. */ }
    } else {
      void SecureStore.setItemAsync(STORAGE_KEY, nextLanguage);
    }
  }

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    hydrated,
    chooseLanguage,
    t: (text: string) => language === 'hi' ? translations[text] ?? text : text,
  }), [hydrated, language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
