import type { ThemeColors } from '@/shared/design-tokens';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View, useWindowDimensions } from 'react-native';

import { AppShell } from '@/components/app-shell';
import { useCustomerStyles } from '@/theme/customer-theme';

type PolicySlug = 'terms' | 'privacy' | 'refund' | 'shipping' | 'warranty';
type PolicySubsection = { title: string; paragraphs?: string[]; items?: string[] };
type PolicySection = { title: string; paragraphs?: string[]; items?: string[]; subsections?: PolicySubsection[] };
type PolicyDefinition = { title: string; lastUpdated: string; intro: string; sections: PolicySection[] };

const contact = {
  email: 'info@sirohipoint.com',
  phone: '+91 9058036895',
  address: 'SHYAMPUR JATT, SALARPUR ROAD, SHYAMPUR JATT, HAPUR, UTTAR PRADESH 245205',
};

const policies: Record<PolicySlug, PolicyDefinition> = {
  terms: {
    title: 'Terms & Conditions', lastUpdated: '22/08/2025', intro: 'These terms explain how the Sirohi Point website and services may be used.', sections: [
      { title: '1. Acceptance of Terms', paragraphs: ['By accessing and using the Sirohi Point website (www.sirohipoint.com) and purchasing our products, you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by the above, please do not use this service.', 'These terms and conditions govern your use of our website and services. We reserve the right to modify these terms at any time without prior notice.'] },
      { title: '2. Company Information', items: [`Business Name: Sirohi Point`, `Address: ${contact.address}, India`, `Email: ${contact.email}`, `Phone: ${contact.phone}`] },
      { title: '3. Definitions', items: ['"Company" refers to Sirohi Point', '"User" refers to anyone who accesses or uses our website', '"Customer" refers to anyone who makes a purchase from us', '"Products" refers to all electronics and accessories sold by us', '"Services" refers to all services provided by our company', '"Website" refers to www.sirohipoint.com'] },
      { title: '4. Eligibility', paragraphs: ['By using our services, you represent and warrant that:'], items: ['You are at least 18 years of age', 'You have the legal capacity to enter into binding contracts', 'All information you provide is accurate and truthful', 'You will comply with all applicable laws and regulations', 'You are not prohibited from using our services under Indian law'] },
      { title: '5. Account Registration', paragraphs: ['To make purchases, you may need to create an account:'], items: ['You are responsible for maintaining account security', 'All information must be accurate and up-to-date', 'You must not share your account credentials', 'We reserve the right to suspend accounts for policy violations', 'One person may maintain only one active account'] },
      { title: '6. Product Information and Pricing', subsections: [{ title: 'Product Descriptions', items: ['We strive to provide accurate product information', 'Colors may vary due to monitor differences', 'Specifications are based on manufacturer data', 'We reserve the right to correct errors'] }, { title: 'Pricing', items: ['All prices are in Indian Rupees (INR)', 'Prices include applicable taxes unless stated otherwise', 'We reserve the right to change prices without notice', 'Promotional prices are valid for limited time', 'Price errors will be corrected before processing orders'] }] },
      { title: '7. Orders and Payment', subsections: [{ title: 'Order Acceptance', items: ['All orders are subject to acceptance and availability', 'We reserve the right to refuse or cancel orders', 'Order confirmation email constitutes acceptance', 'Contract is formed when we ship your order'] }, { title: 'Payment Terms', items: ['Payment must be made in full before shipping', 'We accept major credit/debit cards, UPI, and cash on delivery', 'All transactions are processed securely', 'Failed payments may result in order cancellation'] }] },
      { title: '8. Shipping and Delivery', items: ['Delivery times are estimates and not guarantees', 'Risk of loss transfers to you upon delivery', 'You must inspect packages upon delivery', 'Report damage or missing items within 48 hours', 'Additional charges may apply for remote locations', 'We are not liable for delays caused by external factors'] },
      { title: '9. Intellectual Property', paragraphs: ['All content on our website is protected by intellectual property laws:'], items: ['Trademarks, logos, and brand names are our property', 'Product images and descriptions are protected by copyright', 'You may not use our content without written permission', 'Unauthorized use may result in legal action', 'Third-party trademarks are property of their respective owners'] },
      { title: '10. User Conduct', paragraphs: ['You agree not to:'], items: ['Use the website for illegal purposes', 'Interfere with website security or functionality', 'Upload malicious software or harmful content', 'Impersonate others or provide false information', 'Violate any applicable laws or regulations', 'Attempt to gain unauthorized access to our systems'] },
      { title: '11. Warranties and Disclaimers', subsections: [{ title: 'Product Warranties', items: ['Products come with manufacturer warranties', 'Warranty terms vary by product and brand', 'We facilitate warranty claims but are not responsible for warranty service', 'Misuse voids warranty coverage'] }, { title: 'Service Disclaimers', items: ['Website is provided "as is" without warranties', 'We do not guarantee uninterrupted service', 'Information accuracy is not guaranteed', 'Third-party content is not our responsibility'] }] },
      { title: '12. Limitation of Liability', paragraphs: ['To the maximum extent permitted by law:'], items: ['Our liability is limited to the purchase price of products', 'We are not liable for indirect or consequential damages', 'We do not warrant compatibility with all devices', 'Force majeure events excuse performance delays', 'Time limits apply to claims against us'] },
      { title: '13. Indemnification', paragraphs: ['You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from your use of our website, violation of these terms, or infringement of any rights of others.'] },
      { title: '14. Privacy Policy', paragraphs: ['Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information. By using our services, you consent to our privacy practices as described in our Privacy Policy.'] },
      { title: '15. Governing Law', paragraphs: ['These terms are governed by the laws of India. Any disputes will be subject to the exclusive jurisdiction of courts in Hapur, Uttar Pradesh. If any provision is found invalid, the remaining terms continue in effect.'] },
      { title: '16. Dispute Resolution', subsections: [{ title: 'Customer Service', paragraphs: ['We encourage you to contact our customer service team first to resolve any issues.'] }, { title: 'Mediation', paragraphs: ['If customer service cannot resolve the issue, we prefer mediation before litigation.'] }, { title: 'Jurisdiction', paragraphs: ['Any legal proceedings must be filed in the appropriate courts of Hapur, Uttar Pradesh.'] }] },
      { title: '17. Contact Information', paragraphs: ['If you have questions about these terms and conditions, please contact us:'], items: [`Legal Email: ${contact.email}`, `Customer Service: ${contact.phone}`, `Business Address: ${contact.address}`, 'Business Hours: Monday-Saturday 10 AM - 8 PM'] },
    ],
  },
  privacy: {
    title: 'Privacy Policy', lastUpdated: '22/08/2025', intro: 'This policy explains what information Sirohi Point collects and how we use and protect it.', sections: [
      { title: '1. Information We Collect', paragraphs: ['At Sirohi Point, we collect information to provide better services to our customers. We collect the following types of information:'], subsections: [{ title: 'Personal Information', items: ['Name, email address, phone number, and postal address', 'Payment information including credit/debit card details', 'Account credentials and preferences', 'Communication history with our customer service'] }, { title: 'Technical Information', items: ['IP address, browser type, and device information', 'Website usage data and cookies', 'Purchase history and product preferences'] }] },
      { title: '2. How We Use Your Information', paragraphs: ['We use the collected information for the following purposes:'], items: ['Processing and fulfilling your orders', 'Communicating with you about your purchases and account', 'Providing customer support and technical assistance', 'Improving our website and services', 'Sending promotional offers and newsletters (with your consent)', 'Preventing fraud and ensuring security', 'Complying with legal obligations'] },
      { title: '3. Information Sharing and Disclosure', paragraphs: ['We do not sell, trade, or rent your personal information to third parties. We may share your information only in the following circumstances:'], items: ['With shipping partners to deliver your orders', 'With payment processors to complete transactions', 'With law enforcement when required by law', 'With your explicit consent', 'To protect our rights and prevent fraud'] },
      { title: '4. Data Security', paragraphs: ['We implement appropriate security measures to protect your personal information:'], items: ['SSL encryption for all data transmission', 'Secure servers with restricted access', 'Regular security audits and updates', 'PCI DSS compliance for payment processing', 'Employee training on data protection'] },
      { title: '5. Cookies and Tracking', paragraphs: ['Our website uses cookies and similar tracking technologies to enhance your browsing experience:'], items: ['Essential cookies for website functionality', 'Analytics cookies to understand user behavior', 'Marketing cookies for personalized advertising', 'Preference cookies to remember your settings'], subsections: [{ title: 'Cookie Controls', paragraphs: ['You can control cookie preferences through your browser settings.'] }] },
      { title: '6. Your Rights', paragraphs: ['You have the following rights regarding your personal information:'], items: ['Access: Request copies of your personal data', 'Rectification: Request correction of inaccurate data', 'Erasure: Request deletion of your personal data', 'Portability: Request transfer of your data', 'Objection: Object to processing of your data', 'Restriction: Request limitation of data processing'], subsections: [{ title: 'Exercising Your Rights', paragraphs: [`To exercise these rights, contact us at ${contact.email}`] }] },
      { title: '7. Data Retention', paragraphs: ['We retain your personal information only as long as necessary for the purposes outlined in this policy or as required by law:'], items: ['Account information: Until account deletion', 'Transaction records: 7 years for tax and legal compliance', 'Marketing data: Until you unsubscribe', 'Support communications: 3 years'] },
      { title: '8. Third-Party Services', paragraphs: ['Our website may contain links to third-party services. We are not responsible for the privacy practices of these external sites. We recommend reading their privacy policies before providing any personal information.'] },
      { title: "9. Children's Privacy", paragraphs: ['Our services are not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If we become aware of such data collection, we will take steps to delete the information.'] },
      { title: '10. Changes to Privacy Policy', paragraphs: ['We may update this privacy policy from time to time. We will notify you of any significant changes by posting the new policy on our website and updating the "Last updated" date at the top of this page.'] },
      { title: '11. Contact Information', paragraphs: ['If you have any questions about this privacy policy or our data practices, please contact us:'], items: [`Email: ${contact.email}`, `Phone: ${contact.phone}`, `Address: ${contact.address}`] },
    ],
  },
  refund: {
    title: 'Refund & Cancellation Policy', lastUpdated: '27/08/2025', intro: 'This policy explains how cancellations, returns, and refunds work at Sirohi Point.', sections: [
      { title: '1. Overview', paragraphs: ['We aim to provide a smooth and transparent refund and cancellation experience. This policy explains how cancellations, returns, and refunds work at Sirohi Point.'] },
      { title: '2. Order Cancellation', subsections: [{ title: 'Before Shipment', items: ['Orders can be cancelled within 2 hours of placement without any charges', `To cancel, email us at ${contact.email} with your Order ID`, 'Full refund is issued to the original payment method'] }, { title: 'After Shipment', items: ['Orders cannot be cancelled once shipped', 'You may refuse delivery; the order will be treated as a return per Section 3'] }] },
      { title: '3. Returns & Refunds', subsections: [{ title: 'Eligibility', items: ['Return request must be raised within 7 days of delivery', 'Item must be unused, in original condition with all accessories and packaging', 'Serial numbers, barcodes, and warranty seals must be intact'] }, { title: 'Non-returnable Items', items: ['Damaged items due to misuse or normal wear and tear', 'Products without original packaging/accessories or with tampered serial numbers', 'Personalized or custom-made products', 'Items marked as non-returnable on the product page'] }, { title: 'Process', items: [`Email ${contact.email} with your Order ID, photos (if damaged/defective), and reason`, 'We’ll issue a Return Authorization with instructions and pickup/ship-back details', 'Items are inspected (2-3 business days) after they reach our facility'] }] },
      { title: '4. Refund Timelines & Method', paragraphs: ['Refunds are initiated within 7-10 business days of successful inspection.', 'Refunds are credited to the original payment method only within 7-10 working days.', 'Bank/card processing times may add 3-7 business days.', 'For COD orders, refunds are processed via bank transfer/UPI (details will be requested securely).'], subsections: [{ title: 'Deductions', items: ['Original shipping charges are non-refundable unless the return is due to our error', 'Return shipping is borne by the customer unless the item is defective or wrong', 'Restocking fee may apply (see Section 6)'] }] },
      { title: '5. Damaged, Defective, or Wrong Item', items: ['Report within 48 hours of delivery with photos/videos', 'We Will arrange full refund with priority processing', 'All shipping costs are covered by us for such cases'] },
      { title: '6. Restocking Fee', items: ['Large/oversized items: up to 10% of the product value', 'Missing packaging/accessories: up to 20% of the product value', 'No restocking for defective/wrong items caused by us'] },
      { title: '7. How to Reach Us', paragraphs: ['For cancellations, returns, and refunds, contact:'], items: [`Email: ${contact.email}`, `Phone/WhatsApp: ${contact.phone}`, `Address: ${contact.address}`] },
    ],
  },
  shipping: {
    title: 'Shipping & Delivery Policy', lastUpdated: '22/08/2025', intro: 'We offer shipping services across India to deliver your orders safely and promptly.', sections: [
      { title: '1. Shipping Coverage', paragraphs: ['We offer shipping services across India to deliver your orders safely and promptly.'], subsections: [{ title: 'Delivery Areas', items: ['Local Delivery (Hapur & Surrounding Areas): Same day or next day delivery', 'Uttar Pradesh: 1-3 business days', 'Delhi NCR: 1-2 business days', 'North India: 2-5 business days', 'Pan India: 3-7 business days'] }, { title: 'Shipping Partners', items: ['Professional courier services (Blue Dart, DTDC, Delhivery)', 'India Post for remote locations', 'Local delivery partners for nearby areas', 'Express delivery options available'] }] },
      { title: '2. Shipping Charges', subsections: [{ title: 'Standard Shipping', items: ['Orders above ₹499: Free shipping across India', 'Orders below ₹499: ₹49 shipping charges', 'Local delivery (within 25km): ₹29 shipping charges', 'Cash on Delivery: Additional ₹25 COD charges'] }, { title: 'Express Delivery', items: ['Same Day Delivery (Local): ₹99', 'Next Day Delivery (Delhi NCR): ₹149', 'Express Pan India: ₹199'] }, { title: 'Special Categories', items: ['Fragile Items: Additional ₹50 for special packaging', 'Large Items: Shipping charges calculated by weight/volume', 'International Shipping: Currently not available'] }] },
      { title: '3. Processing Time', subsections: [{ title: 'Order Processing', items: ['In-Stock Items: 1-2 business days', 'Pre-Order Items: As specified on product page', 'Custom Orders: 5-7 business days', 'Gift Wrapping: Additional 1 business day'] }, { title: 'Cut-off Times', items: ['Same Day Delivery: Orders before 12:00 PM', 'Next Day Processing: Orders before 6:00 PM', 'Weekend Orders: Processed on next business day', 'Holiday Orders: May experience delays'] }] },
      { title: '4. Delivery Process', subsections: [{ title: 'Order Tracking', items: ['Tracking number provided via SMS and email', 'Real-time tracking updates', 'Delivery notifications sent before arrival', 'Customer service support for tracking queries'] }, { title: 'Delivery Attempts', items: ['Up to 3 delivery attempts will be made', 'Customer will be contacted before each attempt', 'Alternative delivery arrangements can be made', 'Package will be returned if delivery fails'] }, { title: 'Delivery Requirements', items: ['Valid ID proof required for high-value items', 'Signature confirmation for all deliveries', 'Age verification for restricted products', 'Inspection allowed before accepting delivery'] }] },
      { title: '5. Packaging Standards', subsections: [{ title: 'Secure Packaging', items: ['Bubble wrap and protective padding for fragile items', 'Tamper-evident packaging for all orders', 'Moisture-resistant packaging when required', 'Eco-friendly packaging materials used'] }, { title: 'Product Protection', items: ['Individual wrapping for multiple items', 'Anti-static packaging for electronics', 'Temperature-controlled packaging if needed', 'Insurance coverage for high-value shipments'] }] },
      { title: '6. Special Delivery Services', subsections: [{ title: 'Premium Services', items: ['White Glove Delivery: Setup and installation service', 'Scheduled Delivery: Choose your preferred time slot', 'Weekend Delivery: Saturday delivery available (premium charge)', 'Gift Delivery: Direct delivery to recipient with message'] }, { title: 'Business Services', items: ['Bulk order shipping solutions', 'Corporate delivery accounts', 'Office address delivery', 'Invoice-based shipping for businesses'] }] },
      { title: '7. Address Guidelines', subsections: [{ title: 'Complete Address Requirements', items: ['Full recipient name (as per ID proof)', 'Complete address with landmark', 'PIN code and city information', 'Mobile number for delivery coordination'] }, { title: 'Special Delivery Locations', items: ['Apartments/Societies: Building name and flat number required', 'Office Delivery: Company name and floor details needed', 'PO Box: Not accepted for COD orders', 'Remote Areas: May require additional delivery time'] }] },
      { title: '8. Delivery Issues & Resolution', subsections: [{ title: 'Common Issues', items: ['Package Damaged: Report immediately, full refund arranged', 'Wrong Item Delivered: Return accepted and full refund processed', 'Missing Items: Investigation and resolution within 24 hours', 'Delivery Delays: Compensation as per delay policy'] }, { title: 'Resolution Process', items: ['Report issues within 24 hours of delivery', 'Photo evidence required for damage claims', 'Investigation completed within 48 hours', 'Resolution provided within 3-5 business days'] }] },
      { title: '9. Holiday & Weather Delays', subsections: [{ title: 'Holiday Schedule', items: ['No deliveries on national holidays', 'Limited service during festival seasons', 'Advance notice provided for holiday delays', 'Express delivery may be available for urgent orders'] }, { title: 'Weather Conditions', items: ['Monsoon season may cause delivery delays', 'Natural disasters may temporarily suspend service', 'Alternative arrangements made when possible', 'Customer notification for weather-related delays'] }] },
      { title: '10. Customer Responsibilities', subsections: [{ title: 'At Time of Delivery', items: ['Be available at the provided address', 'Check package condition before signing', 'Verify contents against invoice', 'Report any discrepancies immediately'] }, { title: 'Address Accuracy', items: ['Provide complete and accurate delivery address', 'Update address changes before shipment', 'Ensure recipient availability during delivery hours', 'Additional charges for address changes after dispatch'] }] },
      { title: '11. Contact Information', paragraphs: ['For shipping and delivery related queries:'], items: [`Shipping Support: ${contact.email}`, `Tracking Help: ${contact.phone}`, `WhatsApp Support: ${contact.phone}`, 'Business Hours: Monday-Saturday 10 AM - 8 PM', `Store Address: ${contact.address}`], subsections: [{ title: 'Note', paragraphs: ['Delivery times are estimates and may vary due to unforeseen circumstances. We strive to meet all delivery commitments and will communicate any delays promptly.'] }] },
    ],
  },
  warranty: {
    title: 'Warranty Policy', lastUpdated: '22/08/2025', intro: 'This warranty policy outlines the terms, conditions, and procedures for warranty claims at Sirohi Point.', sections: [
      { title: '1. Warranty Overview', paragraphs: ['At Sirohi Point, we stand behind the quality of our products. All items sold come with manufacturer warranties that protect you against defects in materials and workmanship. This warranty policy outlines the terms, conditions, and procedures for warranty claims.'], subsections: [{ title: "What's Covered", items: ['Manufacturing defects in materials and workmanship', 'Components that fail under normal use conditions', 'Software-related issues covered by manufacturer', 'Battery performance issues (within specified parameters)'] }, { title: "What's Not Covered", items: ['Physical damage from drops, impacts, or accidents', 'Water damage or exposure to liquids', 'Damage from misuse, abuse, or negligence', 'Normal wear and tear', 'Damage from unauthorized repairs or modifications', 'Software issues caused by user error or third-party apps', "Cosmetic damage that doesn't affect functionality"] }] },
      { title: '2. Warranty Periods', paragraphs: ['Warranty periods vary by product category and manufacturer:'], subsections: [{ title: 'Electronics & Mobile Devices', items: ['Smartphones: 1 year from purchase date', 'Tablets: 1 year from purchase date', 'Smartwatches: 1 year from purchase date', 'Headphones/Earphones: 6 months to 1 year (varies by brand)', 'Power Banks: 6 months from purchase date'] }, { title: 'Accessories', items: ['Chargers and Cables: 6 months from purchase date', 'Screen Protectors: 30 days from purchase date', 'Cases and Covers: 3 months from purchase date', 'Mobile Stands: 6 months from purchase date'] }, { title: 'Special Categories', items: ['Extended warranties available for premium products', 'International brands may have different warranty terms', 'Refurbished items: 90 days from purchase date'] }] },
      { title: '3. Warranty Claim Process', subsections: [{ title: 'Step 1: Initial Assessment', items: [`Contact our customer service at ${contact.email}`, 'Provide order number, product details, and issue description', 'Include photos or videos of the defect if applicable', 'Our team will perform initial diagnosis'] }, { title: 'Step 2: Documentation Required', items: ['Original purchase invoice or receipt', 'Product serial number and model information', 'Clear description of the problem or defect', 'Photos/videos demonstrating the issue'] }, { title: 'Step 3: Warranty Approval', items: ['We will verify warranty eligibility within 24-48 hours', 'Approved claims receive a warranty case number', 'Instructions for product return or service will be provided'] }, { title: 'Step 4: Resolution', items: ['Repair: Product will be repaired and returned', 'Replacement: New or refurbished unit provided', 'Refund: Full purchase price refunded (if repair/replacement unavailable)', 'Processing time: 7-14 business days'] }] },
      { title: '4. Service Centers', subsections: [{ title: 'Authorized Service Centers', paragraphs: ['We work with authorized service centers for major brands:'], items: ['Samsung, Apple, OnePlus, Xiaomi authorized centers', 'Local service partners for other brands', 'We facilitate all warranty claims and follow-ups'] }, { title: 'Sirohi Point Service', items: ['In-house technical support for accessories', 'Quick diagnosis and repair services', 'Loaner devices available for premium customers', 'Pick-up and delivery service in local areas'] }] },
      { title: '5. International Warranties', paragraphs: ['For international brand products:'], items: ['Global warranty honored through authorized service centers', 'May require registration with manufacturer', 'Warranty terms follow manufacturer policies', 'We assist with warranty registration and claims', 'Additional documentation may be required'] },
      { title: '6. Extended Warranty Options', subsections: [{ title: 'Premium Protection Plans', items: ['Extended coverage up to 2-3 years', 'Accidental damage protection available', 'Priority service and faster repairs', 'Loaner device programs'] }, { title: 'Coverage Options', items: ['Basic extended warranty: Manufacturing defects only', 'Comprehensive coverage: Includes accidental damage', 'Premium plus: Includes theft protection', 'Business plans: Volume discounts available'] }] },
      { title: '7. Warranty Limitations', subsections: [{ title: 'General Limitations', items: ['Warranty is non-transferable', 'Original purchaser must initiate claims', 'Proof of purchase required for all claims', 'Warranty void if tampered or repaired elsewhere'] }, { title: 'Software Limitations', items: ['Software updates may void certain warranties', 'Root/jailbreak voids software warranty', 'Third-party software damage not covered', 'Data loss not covered under warranty'] }] },
      { title: '8. Data Protection', paragraphs: ['Important information about your data during warranty service:'], items: ['Always backup your data before sending for repair', 'We are not responsible for data loss during service', 'Factory reset may be required for troubleshooting', 'Personal data will be handled confidentially', 'Data recovery services available separately'] },
      { title: '9. Warranty Status Check', paragraphs: ['To check your warranty status:'], items: [`Email ${contact.email} with your order number`, `Call ${contact.phone} during business hours`, 'Visit our store with your purchase receipt', 'Online warranty portal coming soon'] },
      { title: '10. Contact Information', paragraphs: ['For warranty-related queries and claims:'], items: [`Warranty Email: ${contact.email}`, `Customer Service: ${contact.phone}`, `WhatsApp Support: ${contact.phone}`, 'Business Hours: Monday-Saturday 10 AM - 8 PM', `Store Address: ${contact.address}`], subsections: [{ title: 'Note', paragraphs: ['This warranty policy supplements but does not replace manufacturer warranties. Manufacturer terms and conditions apply where applicable.'] }] },
    ],
  },
};

export function PolicyPage({ policy }: { policy: PolicySlug }) {
  const router = useRouter();
  const styles = useCustomerStyles(createStyles);
  const { width } = useWindowDimensions();
  const compact = width < 720;
  const definition = policies[policy];

  return <AppShell>
    <View style={[styles.pageContent, compact && styles.pageContentCompact]}>
      <View style={styles.policyHero}>
        <Text style={styles.eyebrow}>SIROHI POINT / POLICIES</Text>
        <Text accessibilityRole="header" style={[styles.policyTitle, compact && styles.policyTitleCompact]}>{definition.title}</Text>
        <Text style={styles.updated}>Last updated: {definition.lastUpdated}</Text>
        <Text style={styles.intro}>{definition.intro}</Text>
      </View>
      <Pressable accessibilityRole="link" onPress={() => router.push('/company')} style={styles.companyLink}><Text style={styles.companyLinkText}>Company information  ↗</Text></Pressable>
      <View style={styles.policySections}>{definition.sections.map((section) => <View style={styles.policySection} key={section.title}>
        <Text accessibilityRole="header" style={styles.sectionTitle}>{section.title}</Text>
        {section.paragraphs?.map((paragraph) => <Text style={styles.body} key={paragraph}>{paragraph}</Text>)}
        {section.items?.map((item) => <View style={styles.bulletRow} key={item}><Text style={styles.bullet}>•</Text><Text style={styles.body}>{item}</Text></View>)}
        {section.subsections?.map((subsection) => <View style={styles.subsection} key={subsection.title}>
          <Text style={styles.subsectionTitle}>{subsection.title}</Text>
          {subsection.paragraphs?.map((paragraph) => <Text style={styles.body} key={paragraph}>{paragraph}</Text>)}
          {subsection.items?.map((item) => <View style={styles.bulletRow} key={item}><Text style={styles.bullet}>•</Text><Text style={styles.body}>{item}</Text></View>)}
        </View>)}
      </View>)}</View>
    </View>
  </AppShell>;
}

const createStyles = (c: ThemeColors) => StyleSheet.create({
  pageContent: { width: '100%', maxWidth: 1040, alignSelf: 'center', paddingHorizontal: 28, paddingVertical: 42, gap: 18 },
  pageContentCompact: { paddingHorizontal: 16, paddingVertical: 24 },
  policyHero: { backgroundColor: c.primaryDark, borderRadius: 18, padding: 32 },
  eyebrow: { color: c.copperBright, fontSize: 11, fontWeight: '900', letterSpacing: 1.8, marginBottom: 14 },
  policyTitle: { color: '#FFFFFF', fontSize: 45, lineHeight: 52, fontWeight: '900', letterSpacing: -1.4 },
  policyTitleCompact: { fontSize: 31, lineHeight: 37 },
  updated: { color: '#B8C9D9', fontSize: 13, marginTop: 16 },
  intro: { color: '#D8E2EC', fontSize: 15, lineHeight: 24, marginTop: 17, maxWidth: 760 },
  companyLink: { alignSelf: 'flex-start', paddingHorizontal: 4, paddingVertical: 6 },
  companyLinkText: { color: c.teal, fontSize: 14, fontWeight: '800' },
  policySections: { gap: 14 },
  policySection: { backgroundColor: c.surface, borderColor: c.line, borderRadius: 14, borderWidth: 1, padding: 24, gap: 10 },
  sectionTitle: { color: c.cream, fontSize: 22, lineHeight: 28, fontWeight: '900', marginBottom: 3 },
  subsection: { borderTopColor: c.line, borderTopWidth: 1, gap: 8, marginTop: 8, paddingTop: 15 },
  subsectionTitle: { color: c.teal, fontSize: 15, lineHeight: 21, fontWeight: '900' },
  body: { color: c.muted, flex: 1, fontSize: 15, lineHeight: 24 },
  bulletRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 9 },
  bullet: { color: c.copperBright, fontSize: 20, lineHeight: 24, width: 10 },
});


