import type { ThemeColors } from '@/shared/design-tokens';
import { useLocalSearchParams, usePathname, useRouter } from 'expo-router';
import Head from 'expo-router/head';
import { SymbolView } from 'expo-symbols';
import { useEffect, useState, type ReactNode } from 'react';
import { Image, Keyboard, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions, type StyleProp, type ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '@/state/auth-context';
import { useAppState } from '@/state/app-context';
import { useBusinessStyles } from '@/theme/business-theme';

const links = [
  { label: 'Home', href: '/business', icon: { ios: 'house', android: 'home', web: 'home' } },
  { label: 'Shop', href: '/business/catalog', icon: { ios: 'bag', android: 'shopping_bag', web: 'shopping_bag' } },
  { label: 'My orders', href: '/business/orders', icon: { ios: 'shippingbox', android: 'inventory_2', web: 'inventory_2' } },
  { label: 'Account', href: '/business/profile', icon: { ios: 'person.crop.circle', android: 'account_circle', web: 'account_circle' } },
] as const;

export function PortalShell({ eyebrow, title, copy, children, actions, includeSignOut = true }: {
  eyebrow: string; title: string; copy: string; children: ReactNode; actions?: ReactNode; includeSignOut?: boolean;
}) {
  const styles = useBusinessStyles(createStyles);
  const router = useRouter();
  const pathname = usePathname();
  const params = useLocalSearchParams<{ q?: string }>();
  const { width } = useWindowDimensions();
  const compact = width < 700;
  const { user, logout } = useAuth();
  const { cartCount, notice, dismissNotice } = useAppState();
  const signedIn = user?.role === 'BUSINESS';
  const [search, setSearch] = useState(params.q ?? '');
  useEffect(() => setSearch(params.q ?? ''), [params.q]);
  const go = (href: string) => router.push(href as never);
  function searchShop() { Keyboard.dismiss(); router.push({ pathname: '/business/catalog', params: { q: search.trim() } }); }
  const searchBar = <View style={styles.search}><TextInput accessibilityLabel="Search wholesale products" value={search} onChangeText={setSearch} placeholder="Search materials, brands & essentials" placeholderTextColor={styles.muted.color} autoCapitalize="none" returnKeyType="search" onSubmitEditing={searchShop} style={styles.searchInput} /><Pressable accessibilityRole="button" accessibilityLabel="Search B2B store" onPress={searchShop} style={styles.searchButton}><SymbolView name={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} size={21} tintColor="#FFFFFF" /></Pressable></View>;
  return <><Head><title>{title} | Sirohi Point Business</title></Head><SafeAreaView edges={['top', 'left', 'right', 'bottom']} style={styles.page}>
    {/* <View style={styles.announcement}><Text style={styles.announcementText}>THE SAME SIROHI. BUILT FOR YOUR BUSINESS.</Text>{!compact ? <Text style={styles.announcementMeta}>Wholesale prices  ·  Bulk buying  ·  GST-ready orders</Text> : null}</View> */}
    <View style={styles.header}><View style={[styles.headerInner, compact && [styles.compactPadding, { gap: 12 }]]}>
      <Pressable accessibilityRole="link" accessibilityLabel="Sirohi Point business home" onPress={() => go(signedIn ? '/business' : '/business/login')} style={styles.brand}><Image source={require('../../../assets/images/logo_sirohi.png')} style={styles.logo} resizeMode="contain" /><View><Text style={[styles.wordmark, compact && { fontSize: 16 }]}>SIROHI POINT<Text style={styles.orange}>.</Text></Text><Text style={styles.brandCaption}>B U S I N E S S</Text></View></Pressable>
      {!compact && signedIn ? searchBar : null}
      <View style={styles.headerActions}>{signedIn ? <><Pressable accessibilityRole="link" accessibilityLabel="Business account" onPress={() => go('/business/profile')} style={[styles.account, compact && { display: 'none' }]}><SymbolView name={{ ios: 'person.crop.circle', android: 'account_circle', web: 'account_circle' }} size={24} tintColor={styles.heading.color} />{width >= 1050 ? <View><Text style={styles.muted}>Hello, {user.name.split(' ')[0]}</Text><Text style={styles.accountLabel}>Your business</Text></View> : null}</Pressable><Pressable accessibilityRole="link" accessibilityLabel={`Bulk cart, ${cartCount} items`} onPress={() => go('/business/cart')} style={styles.cart}><SymbolView name={{ ios: 'cart', android: 'shopping_cart', web: 'shopping_cart' }} size={21} tintColor="#FFFFFF" />{!compact ? <Text style={styles.whiteLabel}>Bulk cart</Text> : null}<Text style={styles.cartCount}>{cartCount}</Text></Pressable></> : <><PortalButton label={compact ? 'Sign in' : 'Business sign in'} secondary onPress={() => go('/business/login')} /><Pressable accessibilityRole="link" accessibilityLabel={`Bulk cart, ${cartCount} items`} onPress={() => go('/business/cart')} style={styles.cart}><SymbolView name={{ ios: 'cart', android: 'shopping_cart', web: 'shopping_cart' }} size={21} tintColor="#FFFFFF" />{!compact ? <Text style={styles.whiteLabel}>Bulk cart</Text> : null}<Text style={styles.cartCount}>{cartCount}</Text></Pressable></>}</View>
    </View>{compact && signedIn ? <View style={styles.mobileSearch}>{searchBar}</View> : null}</View>
    {signedIn ? <View style={styles.nav}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.navInner}>{links.map(link => { const active = pathname === link.href || (link.href === '/business/catalog' && pathname.startsWith('/business/product/')); return <Pressable key={link.href} accessibilityRole="link" accessibilityState={{ selected: active }} onPress={() => go(link.href)} style={[styles.navLink, active && styles.navActive]}><Text style={[styles.navText, active && styles.orange]}>{link.label}</Text></Pressable>; })}<Pressable accessibilityRole="link" accessibilityLabel="Open bulk cart" accessibilityState={{ selected: pathname === '/business/cart' }} onPress={() => go('/business/cart')} style={[styles.navLink, pathname === '/business/cart' && styles.navActive]}><View style={styles.navCart}><SymbolView name={{ ios: 'cart', android: 'shopping_cart', web: 'shopping_cart' }} size={18} tintColor={pathname === '/business/cart' ? styles.orange.color : styles.navText.color} /><Text style={[styles.navText, pathname === '/business/cart' && styles.orange]}>Cart ({cartCount})</Text></View></Pressable>{includeSignOut ? <Pressable accessibilityRole="button" onPress={() => void logout().then(() => router.replace('/business/login'))} style={styles.navLink}><Text style={styles.muted}>Sign out ↗</Text></Pressable> : null}</ScrollView></View> : null}
    <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">
      <View style={[styles.content, compact && styles.compactPadding]}>
        <View style={styles.pageHeading}><View style={styles.headingBody}><Text style={styles.eyebrow}>{eyebrow}</Text><Text accessibilityRole="header" style={[styles.heading, compact && styles.headingCompact]}>{title}</Text><Text style={styles.copy}>{copy}</Text></View>{actions ? <View style={styles.actions}>{actions}</View> : null}</View>
        {children}
      </View>
      <View style={styles.footer}><View style={styles.footerInner}><View style={styles.footerBrand}><Text style={styles.footerWordmark}>SIROHI POINT<Text style={styles.orange}>.</Text></Text><Text style={styles.footerTitle}>Big plans. Better buying.</Text><Text style={styles.footerCopy}>The essentials your business needs, all in one place.</Text></View><View style={styles.footerColumn}><Text style={styles.footerLabel}>YOUR BUSINESS STORE</Text>{links.slice(1).map(link => <Pressable key={link.href} accessibilityRole="link" onPress={() => go(signedIn ? link.href : '/business/login')} style={styles.footerLink}><Text style={styles.footerCopy}>{link.label} ↗</Text></Pressable>)}</View><View style={styles.footerColumn}><Text style={styles.footerLabel}>BUILT AROUND YOUR WORK</Text><Text style={styles.footerCopy}>Clear wholesale rates{ '\n' }Minimum quantities upfront{ '\n' }Orders you can follow, every step</Text></View><View style={styles.footerColumn}><Text style={styles.footerLabel}>PRIVACY &amp; POLICY</Text><Pressable accessibilityRole="link" onPress={() => go('/privacy')} style={styles.footerLink}><Text style={styles.footerCopy}>Privacy policy ↗</Text></Pressable><Pressable accessibilityRole="link" onPress={() => go('/terms')} style={styles.footerLink}><Text style={styles.footerCopy}>Terms &amp; conditions ↗</Text></Pressable></View></View><View style={styles.footerBottom}><Text style={styles.footerSmall}>© {new Date().getFullYear()} Sirohi Point. All rights reserved. • WEBSITE BY SIROHI HARDWARE AND ELECTRICS POINT</Text></View></View>
    </ScrollView>
    {signedIn && compact ? <View style={styles.bottomNav}>{links.map(link => <Pressable key={link.href} accessibilityRole="link" accessibilityState={{ selected: pathname === link.href }} onPress={() => go(link.href)} style={styles.bottomLink}><SymbolView name={link.icon} size={20} tintColor={pathname === link.href ? styles.orange.color : styles.muted.color} /><Text style={[styles.bottomLabel, pathname === link.href && styles.orange]}>{link.label === 'Business account' ? 'Account' : link.label === 'Shop wholesale' ? 'Shop' : link.label}</Text></Pressable>)}</View> : null}
    {notice ? <View accessibilityRole="alert" style={[styles.toast, compact && { bottom: 78 }]}><Text style={styles.toastText}>{notice}</Text><Pressable accessibilityRole="button" accessibilityLabel="Dismiss notification" onPress={dismissNotice} style={styles.dismiss}><Text style={styles.whiteLabel}>×</Text></Pressable></View> : null}
  </SafeAreaView></>;
}

export function PortalCard({ title, copy, children, style }: { title?: string; copy?: string; children?: ReactNode; style?: StyleProp<ViewStyle> }) {
  const styles = useBusinessStyles(createStyles);
  return <View style={[styles.card, style]}>{title ? <Text accessibilityRole="header" style={styles.cardTitle}>{title}</Text> : null}{copy ? <Text style={styles.cardCopy}>{copy}</Text> : null}{children}</View>;
}
export function PortalMetric({ value, label }: { value: string; label: string }) {
  const styles = useBusinessStyles(createStyles);
  return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.cardCopy}>{label}</Text></View>;
}
export function PortalButton({ label, onPress, secondary = false, danger = false, disabled = false, compact = false }: { label: string; onPress(): void; secondary?: boolean; danger?: boolean; disabled?: boolean; compact?: boolean }) {
  const styles = useBusinessStyles(createStyles);
  return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, compact && { minHeight: 34, paddingHorizontal: 8, paddingVertical: 7, borderRadius: 8 }, secondary && styles.buttonSecondary, danger && styles.buttonDanger, pressed && { opacity: 0.78 }, disabled && { opacity: 0.45 }]}><Text style={[styles.buttonText, compact && { fontSize: 10 }, secondary && styles.buttonTextSecondary, danger && styles.dangerText]}>{label}</Text></Pressable>;
}
export function StatusBadge({ label, tone = 'neutral' }: { label: string; tone?: 'neutral' | 'success' | 'warning' | 'danger' }) {
  const styles = useBusinessStyles(createStyles);
  return <View style={[styles.badge, tone === 'success' && styles.badgeSuccess, (tone === 'warning' || tone === 'danger') && styles.badgeWarm]}><Text style={[styles.badgeText, tone === 'success' && styles.successText, tone === 'warning' && styles.orange, tone === 'danger' && styles.dangerText]}>{label.replace(/_/g, ' ')}</Text></View>;
}

const createStyles = (c: ThemeColors) => StyleSheet.create({
  page: { flex: 1, backgroundColor: c.ink }, scroll: { flex: 1 }, scrollContent: { flexGrow: 1 },
  announcement: { backgroundColor: '#102237', paddingHorizontal: 24, paddingVertical: 10, flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, announcementText: { color: '#DFE8F2', fontSize: 10, letterSpacing: 1.5, fontWeight: '700' }, announcementMeta: { color: '#B5C5D7', fontSize: 11 },
  header: { backgroundColor: c.header }, headerInner: { width: '100%', maxWidth: 1440, alignSelf: 'center', paddingHorizontal: 28, paddingVertical: 20, flexDirection: 'row', alignItems: 'center', gap: 28 }, compactPadding: { paddingHorizontal: 16 }, brand: { flexDirection: 'row', alignItems: 'center', gap: 9 }, logo: { width: 40, height: 40, borderRadius: 9, backgroundColor: '#FFFFFF' }, wordmark: { color: c.cream, fontSize: 21, fontWeight: '900', letterSpacing: -0.8 }, brandCaption: { color: c.muted, fontSize: 9, marginTop: 4, fontWeight: '700' }, orange: { color: c.copper },
  search: { flex: 1, flexDirection: 'row', minWidth: 0, minHeight: 48, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: c.line, backgroundColor: c.surfaceRaised }, searchInput: { flex: 1, minWidth: 0, paddingHorizontal: 16, fontSize: 14, color: c.cream }, searchButton: { width: 50, alignItems: 'center', justifyContent: 'center', backgroundColor: c.cta }, mobileSearch: { paddingHorizontal: 16, paddingBottom: 16, flexDirection: 'row' }, headerActions: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', gap: 16 }, account: { flexDirection: 'row', alignItems: 'center', minHeight: 44, gap: 8 }, accountLabel: { color: c.cream, fontSize: 13, fontWeight: '700' }, muted: { color: c.muted, fontSize: 12 }, cart: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 46, backgroundColor: c.primary, borderRadius: 12, paddingHorizontal: 13 }, whiteLabel: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' }, cartCount: { color: '#FFFFFF', backgroundColor: c.cta, borderRadius: 20, padding: 4, minWidth: 24, textAlign: 'center', fontSize: 12, fontWeight: '700' },
  nav: { backgroundColor: c.header, borderTopWidth: 1, borderBottomWidth: 1, borderColor: c.line }, navInner: { paddingHorizontal: 16, flexGrow: 1, gap: 8 }, navLink: { minHeight: 50, paddingHorizontal: 15, justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' }, navActive: { borderBottomColor: c.cta }, navText: { color: c.cream, fontSize: 13, fontWeight: '700' }, navCart: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  content: { width: '100%', maxWidth: 1440, alignSelf: 'center', paddingHorizontal: 28, paddingBottom: 32, gap: 24, flexGrow: 1 }, pageHeading: { paddingTop: 30, paddingBottom: 4, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 20 }, headingBody: { flex: 1, minWidth: 240, gap: 8 }, eyebrow: { color: c.copper, fontSize: 10, letterSpacing: 1.8, fontWeight: '800' }, heading: { color: c.cream, fontSize: 34, lineHeight: 42, fontWeight: '800', letterSpacing: -1 }, headingCompact: { fontSize: 27, lineHeight: 34 }, copy: { color: c.muted, fontSize: 14, lineHeight: 22, maxWidth: 690 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  card: { padding: 24, borderRadius: 20, borderWidth: 1, borderColor: c.line, backgroundColor: c.surface, gap: 16, minWidth: 0 }, cardTitle: { color: c.cream, fontSize: 21, fontWeight: '800', letterSpacing: -0.4 }, cardCopy: { color: c.muted, fontSize: 13, lineHeight: 21 }, metric: { flexGrow: 1, flexBasis: 140, padding: 20, borderRadius: 16, backgroundColor: c.surface, borderWidth: 1, borderColor: c.line, gap: 8 }, metricValue: { color: c.cream, fontSize: 28, fontWeight: '800', letterSpacing: -0.6 },
  button: { minHeight: 46, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 11, backgroundColor: c.cta, alignItems: 'center', justifyContent: 'center' }, buttonSecondary: { backgroundColor: c.surface, borderWidth: 1, borderColor: c.line }, buttonDanger: { backgroundColor: c.surface, borderWidth: 1, borderColor: c.danger }, buttonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700', textAlign: 'center' }, buttonTextSecondary: { color: c.cream }, dangerText: { color: c.danger }, badge: { alignSelf: 'flex-start', borderRadius: 20, backgroundColor: c.surfaceSunken, paddingHorizontal: 10, paddingVertical: 7 }, badgeText: { color: c.muted, fontSize: 10, fontWeight: '700' }, badgeSuccess: { backgroundColor: c.successTint }, badgeWarm: { backgroundColor: c.copperTint }, successText: { color: c.success },
  footer: { backgroundColor: '#102237', paddingHorizontal: 28, paddingTop: 40, marginTop: 16 }, footerInner: { width: '100%', maxWidth: 1384, alignSelf: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 32, paddingBottom: 32 }, footerBrand: { flexGrow: 2, flexBasis: 260, gap: 12 }, footerWordmark: { color: '#FFFFFF', fontSize: 23, fontWeight: '900' }, footerTitle: { color: '#FFFFFF', fontSize: 22, fontWeight: '600' }, footerCopy: { color: '#B5C5D7', fontSize: 13, lineHeight: 24 }, footerColumn: { flex: 1, minWidth: 210, gap: 12 }, footerLabel: { color: '#FFFFFF', fontSize: 10, letterSpacing: 1.5, fontWeight: '700' }, footerLink: { minHeight: 34, justifyContent: 'center' }, footerBottom: { maxWidth: 1384, width: '100%', alignSelf: 'center', paddingVertical: 20, borderTopWidth: 1, borderColor: '#2A3E55', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap', gap: 12 }, footerSmall: { color: '#A5B7CD', fontSize: 11, lineHeight: 18, textAlign: 'center' }, bottomNav: { flexDirection: 'row', backgroundColor: c.header, borderTopWidth: 1, borderColor: c.line }, bottomLink: { flex: 1, minHeight: 62, alignItems: 'center', justifyContent: 'center', gap: 5 }, bottomLabel: { color: c.muted, fontSize: 10, fontWeight: '700' }, toast: { position: 'absolute', bottom: 24, left: 16, right: 16, maxWidth: 580, alignSelf: 'center', backgroundColor: '#182D45', borderRadius: 14, paddingLeft: 20, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 8 }, toastText: { flex: 1, color: '#FFFFFF', fontSize: 14, lineHeight: 21 }, dismiss: { width: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
});

